### ISSUE TITLE
Full name välja kuvamine grupi esilehel

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#215]
Grupi esilehel grupi liikmete nimekirjas kuvada kasutaja Full Name välja väärtus, mitte FB või Google-st pärit info (juhul kui kasutaja on ise Full Name välja muutnud).

**Comment by pjotrsavitski** [comment]
Vastava vaade on täies mahus muudetud. Nüüd kasutatakse ainult täisnime, meie loogika järgi.
