### ISSUE TITLE
Leivapuru Grupi nimi -> group all

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#261]
Tekitada leivapuru või "tagasi grupi esilehele" link järgmiste menüüpunktide alla:

Grupi nimi -> group -> add people
Grupi nimi -> group -> people
Grupi nimi -> group -> permissions
Grupi nimi -> group -> roles

![screen shot 2014-08-25 at 22 02 18](https://cloud.githubusercontent.com/assets/380007/4034968/626171a6-2c8a-11e4-9e59-846216debb85.png)

**Comment by RKoitsalu** [comment]
#285
