### ISSUE TITLE
Grupi menüü kuvamine alamlehtedel

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#285]
Kuvada grupimenüü (kuva, muuda, grupp, ajaveeb jne..) viidatud alamlehtedel:

![screen shot 2014-10-14 at 15 21 40](https://cloud.githubusercontent.com/assets/380007/4628854/dc25a0aa-539c-11e4-9741-a19c3bb328d1.png)

**Comment by RKoitsalu** [comment]
Kasutajad lehele ei ole võimalik midagi lisada hetkel.
