### ISSUE TITLE
Õppematerjalide tüübid, uuendatud nimekiri

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#293]
Õppematerjalide tüübid viia vastavusse järgmise nimekirjaga:
- Esitlus
- Harjutus
- Heli
- Illustratsioon
- Tekst
- Simulatsioon
- Veebileht
- Video
- Muu

**Comment by RKoitsalu** [comment]
Uuendus tehtud serveris kasutajaliidese abiga.
