### ISSUE TITLE
Uue ülesande lisamisel gruppi kuvatakse veateade

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#301]
![screenshot-ubpflyo2z0agpjq1itznayetccbm56cntbt75nc3mvcldfictu1415527021040](https://cloud.githubusercontent.com/assets/380007/4967209/4098ab1e-6800-11e4-8e9c-1d2b5fe93669.png)

**Comment by RKoitsalu** [comment]
Ei õnnestunud viga taastekitada. Avada pilet uuesti, kui viga kordub
