### ISSUE TITLE
Uue alamgrupi loomine

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#320]
Uue alamgrupi loomisel kuvatakse kasutajale järgmist vaadet:
![screen shot 2015-01-25 at 22 58 15](https://cloud.githubusercontent.com/assets/380007/5893267/e1074fe8-a4e5-11e4-8af9-823beb62bc0b.png)

**Comment by RKoitsalu** [comment]
Lülitasin alamgruppide mooduli sisse. Peaks nüüd toimima.
