### ISSUE TITLE
E-posti aadressi kuvamine kasutaja profiili all

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#323]
Kuvada sisseloginud kasutajatele kasutaja profiilis e-posti aadressi.

![screen shot 2015-02-04 at 14 56 17](https://cloud.githubusercontent.com/assets/380007/6040781/6849f65a-ac7e-11e4-91c1-412d4bee4a33.png)

**Comment by pjotrsavitski** [comment]
Arvan et oleks vaja lahendust mis ei lubaks robotitel neid aadresse lugemas käima.

**Comment by RKoitsalu** [comment]
Roboteid ei tasu karta. Sisselogimata kasutaja saab "access denied" profiili lehte vaadates
