### ISSUE TITLE
Õppematerjalide kogumik

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#330]
Kogumik on õppematerjalide kollektsioon. Kõik õppejõu rollis kasutajad saavad luua kogumikke.

Kogumiku loomiseks on kaks võimalust:
- lisa uus kogumik kasutaja töölaualt
- lisa uus kogumik kogumikkude nimekirjast

![screen shot 2015-02-25 at 13 14 56](https://cloud.githubusercontent.com/assets/380007/6369566/4f62a326-bcf0-11e4-9798-dd60d1b42afa.png)

![screen shot 2015-02-25 at 13 15 09](https://cloud.githubusercontent.com/assets/380007/6369575/5b2ec658-bcf0-11e4-9992-0f80dff858d2.png)

Kogumik koosneb:
- kaanepilt
- taustapilt
- pealkiri
- lühikirjeldus
- kogumikku lisatud õppematerjalidest

Kogumiku vaates kuvatakse lisaks eelpool mainutud infole ka lisatud materjalide vaatamiste ja meeldimiste arv koos materjali autori ning pealkirja-kaanepildiga.

![screen shot 2015-02-25 at 13 12 34](https://cloud.githubusercontent.com/assets/380007/6369527/fbccf568-bcef-11e4-8d08-b2963c579100.png)

Õppematerjale kogumikku lisatakse õppematerjali vaatest. Lisada saab nii kasutaja enda poolt kui teiste kasutajate poolt loodud ja avaldatud materjale.

![screen shot 2015-02-25 at 13 14 10](https://cloud.githubusercontent.com/assets/380007/6369557/35278e68-bcf0-11e4-8008-1279a0977c2b.png)

![screen shot 2015-02-25 at 13 14 29](https://cloud.githubusercontent.com/assets/380007/6369561/4015b976-bcf0-11e4-9cd8-ca3ac0597cb5.png)

Kogumikkude nimekirjas kuvatakse vaid kogumikud, mis on esile tõstetud keskkonna haldaja poolt (sarnaselt esiletõstetud uudiste ja õppematerjalidega).

**Comment by pjotrsavitski** [comment]
Kas kogumikku materjali lisamine käib ainult materjali vaatest?
Kui kogumik on administraatori poolt kinnitatud, kas looja saab seda ikka muuta või võetakse selline võimalus ära?

**Comment by tammets** [comment]
Jah, materjali vaatest ja looja saab hiljem ka muuta.
