### ISSUE TITLE
Portfoolio pädevusprofiil

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#331]
Portfoolio juures on võimalik kasutajal määrata, kas kuvatakse ka seotud pädevused. Juhul kui kasutaja selle valiku määrab, kuvatakse portfooliol ka avalikus vaates kaks sakki - esileht ning pädevuste ülevaade.

![screen shot 2015-02-25 at 14 00 30](https://cloud.githubusercontent.com/assets/380007/6370548/701bbb8e-bcfa-11e4-82dc-1600e8c19f0d.png)

![screen shot 2015-02-25 at 14 09 24](https://cloud.githubusercontent.com/assets/380007/6370551/7424ebba-bcfa-11e4-90dd-1de037504406.png)

**Comment by RKoitsalu** [comment]
Arvatavasti peab pädevuse taksonoomia terminitel olema võimalik seadistuses värvi valida.

Kuidas töötab pädevuste riba portfoolio kuvamise vaates?

**Comment by tammets** [comment]
Lisamooduli kasutamine ei ole hea mõte mu hinnangul. Teine variant on parem, kasutaja ei pea valima värve.

Pädevuste riba kuvamise vaates annab ülevaate proportsioonis vastavalt omandatud mudeli osadele. St mitu % moodustab iga tükk tervikust (100%). Täpsema vaate saab kasutaja kui avab pödevusprofiili kas klikates nimetatud sakile või pädevuste ribal.

**Comment by RKoitsalu** [comment]
Üks asi on veidi segaseks jäänud siiski. Kust tuleb see tekst, mis on pildil tõendite tabelist üleval pool?

**Comment by tammets** [comment]
See on termi description.
