### ISSUE TITLE
Feedback link eesti keeles

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#332]
Kuvada feedback-widgeti link eesti keelses kasutajaliideses eesti keeles.

**Comment by pjotrsavitski** [comment]
See ei paista võimalik olevat. Element ise tundub olevat pilt. Kuna sisu on eestikeelne, siis keelesättet ikkagi edastatakse. Pole ehk teenuse poolt võimaldatud.
