### ISSUE TITLE
Alamgrupi avaleht viia vastavusse nn tavagrupi avalehe vaatega

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#337]
Välja arvatud nn "puuduolevad" funktsionaalsused:

![screen shot 2015-03-11 at 12 35 37](https://cloud.githubusercontent.com/assets/380007/6594601/52cdd764-c7eb-11e4-9e3b-32980233574f.png)

**Comment by RKoitsalu** [comment]
duplicate #343
