### ISSUE TITLE
Grupi esileht - liitu grupiga link

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#339]
Peaks omama css-klassi:

![screen shot 2015-03-24 at 10 06 30](https://cloud.githubusercontent.com/assets/380007/6797689/a4492720-d20d-11e4-9f46-e1ddf1b11a8e.png)

**Comment by RKoitsalu** [comment]
On võimalik see kätte saada selectoriga **.field-item a.subscribe**
