### ISSUE TITLE
Cahce / failide jagamine grupiga

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#340]
Failide jagamisel grupiga võib tekkida probleem, kus õppejõud jagab grupiga faili kuid tudengid ei saa sellele ligi. Käsitsi lahendus oli tühjendada cahce (*flush all caches*).

**Comment by RKoitsalu** [comment]
Kuidas proovivad tudengid file nodele ligi pääseda? Kas õpetaja jagab neile linki, või proovivad nad pääseda selleni läbi grupi?
Kui esimene variant, siis milline näeb link välja? kas node/NID või content/LOODUD_SISU_NIMI ?

**Comment by RKoitsalu** [comment]
content/LOODUD_SISU_NIMI
