### ISSUE TITLE
Veateade pädevusprofiili vaates (portfoolio)

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#342]
Lisades olemasolevale portfooliole pädevusprofiili (märkeruut) ja salvestades, kuvatakse järgmine veateade:

![screen shot 2015-04-08 at 9 56 11](https://cloud.githubusercontent.com/assets/380007/7040322/5feff70a-ddd6-11e4-80f2-66d9e2692f99.png)

**Comment by RKoitsalu** [comment]
Administreerimisliideses palun sättida värvid kõikidele pädevuse ülemtermidele

**Comment by tammets** [comment]
Administreerimisliideses sättida värvid kõikidele pädevuse ülemtermidele.
