### ISSUE TITLE
Ülesandele vastamine - veateade vastuse salvestamisel

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#353]
Lokaalselt, mitte ed.ee-s.

![screen shot 2015-08-10 at 9 51 54](https://cloud.githubusercontent.com/assets/380007/9160741/b3d7df56-3f45-11e5-94af-3efedbc87109.png)

**Comment by pjotrsavitski** [comment]
Tundub et sul on vastav tabel loomata. Selle välja uurimiseks peaks koodi vaatama.

Julgen oletada et tegemist on muudatusega mille jaoks kas pole migratsiooni tehtud või see ebaõnnestus (või jäi käiku laskmata).

**Comment by tammets** [comment]
Lahendatud, tänan.
