### ISSUE TITLE
Grupi määramine ülesande vastuse juures

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#370]
Ülesande vastuse juures arvestada gruppi, mille on määranud ülesande looja - vastuse sisestaja ei tohi saada eemaldada või lisada gruppe. Kasutaja määramine toimib endiselt.

Probleemiks on vastused, millele on määratud grupp, kuhu hindav õppejõud ei kuulu. Sellisel juhul hetkel õppejõud vastuse staatust muuta ei saa.

Kattub piletiga #357 ja sulgeb selle.

**Comment by GlebRed** [comment]
Juhul kui ülesanne on jagatud mitu gruppidega, valitakse ainult esimese gruppi nimekirjast (kastist) suvalisena ja peidetakse selle kasti ära. Seepärast kui kasutaja salvestab vastust (kus on siis vale grupp valitud) tuleb permissioni viga 

> The referenced group (node XXX) is invalid
