### ISSUE TITLE
Kasutajal ei ole võimalik tekstikasti lisada embed-sisu

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#377]

**Comment by GlebRed** [comment]
Nüüd suppordib YouTube, Vimeo, EDpuzzle, Google Maps, SlideShare embeddimist

**Comment by GlebRed** [comment]
Google Docs lisatud

**Comment by tammets** [comment]
Lisatud Powtoon.com

**Comment by GlebRed** [comment]
Lisatud Storybird.com, Onedrive.live.com

**Comment by tammets** [comment]
`%^(https?:)?//(www\.youtube(?:-nocookie)?\.com/embed/|player\.vimeo\.com/video/|edpuzzle\.com/embed/|www\.google(?:-nocookie)?\.com/maps/|www\.slideshare(?:-nocookie)?\.net/|docs\.google(?:-nocookie)?\.com/document/|www\.powtoon(?:-nocookie)?\.com/embed/|onedrive\.live(?:-nocookie)?\.com/|storybird(?:-nocookie)?\.com/books/|app\.emaze(?:-nocookie)?\.com/|e\.issuu\.com/)%`
