### ISSUE TITLE
Grupi vaade - "Active group"

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#382]
Paremal paanil olevat märget "Active group" ei saa tõlkida:

![screen shot 2016-01-11 at 12 08 59](https://cloud.githubusercontent.com/assets/380007/12230915/373bc49a-b85c-11e5-9d03-a2711b67cd98.png)

**Comment by pjotrsavitski** [comment]
Vaade on korralikult muutunud, vastavat elementi ei paista enam olevat.
