### ISSUE TITLE
Alamgrupi nähtavus

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#383]
Alamgrupi loomisel eemaldada Grupi nähtavus ja seada vaikimisi väärtuseks "Privaatne - ligipääs on ainult grupi liikmetel" kuna alamgrupid toimivad vaid koos nn peagrupiga alati.

![screen shot 2016-01-11 at 13 15 29](https://cloud.githubusercontent.com/assets/380007/12232174/920c92d8-b865-11e5-956f-3aec6cb0539f.png)

**Comment by pjotrsavitski** [comment]
Kas vastav issue on üldse pädev? Eks ta epaks suhteliselt lihtne olema, kuid me oleme alamgruppe enamasti maha akndnud.

**Comment by tammets** [comment]
Pilet kinni, kuna alamgrupide funktsionaalsus kaob.
