### ISSUE TITLE
Keelte valik õppematerjali sisestamisel

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#391]
Lisada õppematerjali sisestamise / muutmise vaatesse lisaks olemasolevatele keeltele ka prantsuse, saksa ja soome.

![screen shot 2016-01-29 at 15 03 51](https://cloud.githubusercontent.com/assets/380007/12676301/ba97242e-c699-11e5-9c74-e357729d998b.png)

**Comment by Industrality** [comment]
Referenced in 06a0404
