### ISSUE TITLE
Grupp - ülesannete vaade, värvikoodid (tudeng)

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#397]
Tudengi vaade viia vastavusse töölaua vaatega:

**Dashboard:**

![screen shot 2016-09-30 at 9 14 10](https://cloud.githubusercontent.com/assets/380007/18982382/515a3e9a-86ee-11e6-9d3b-8c7fac2d0277.png)

**Grupi ülesanded:**

![screen shot 2016-09-30 at 9 14 16](https://cloud.githubusercontent.com/assets/380007/18982387/5cc9e654-86ee-11e6-92b6-beaec481ae90.png)

**Comment by GlebRed** [comment]
https://github.com/centre-for-educational-technology/edidaktikum_theme/commit/b49b615a16e040bf1b887ebb29b043a7660a9a46
