### ISSUE TITLE
Sisu, kommentaarikasti ja külgpaani asetus

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#408]
Kasutajale kuvada külgpaani kasutatavad leheküljed järgmise asetusega (hetkel kommentaarikast laiusega 100% peale sisu ja külgpaani, mis "pika" külgpaani korral kommentaarikasti liialt "kaugel kuvab"):

![screen shot 2016-04-04 at 10 48 05](https://cloud.githubusercontent.com/assets/380007/14241217/ffc73254-fa52-11e5-900c-68959c9ca20e.png)

**Comment by tammets** [comment]
Ülesande vastus, õppematerjal, Arutelu (foorum), järjehoidja

**Comment by hazarada** [comment]
Vahetasin paneelide layouti answers, bookmark ja forum lehekülgedel. Grep ütleb, et vana layouti kasutavad veel blog, cluster, collection, event, file, learning resource, portfolio, task ja subgroup aga nende puhul probleemi ei näinud.

**Comment by hazarada** [comment]
Tarvis olev layout on olemas (edidaktikum_theme e6b6ffccc3edcff8bbb58f1581fcec742f79d2c9 twocol_stacked_top) aga hetkel pole tarvis
