### ISSUE TITLE
Pädevuste nimekiri küljepaanil vaikimisi peitu

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#409]
![screen shot 2016-04-04 at 11 12 13](https://cloud.githubusercontent.com/assets/380007/14241799/340fea4e-fa56-11e5-9767-d33d29c91a64.png)

**Comment by hazarada** [comment]
closed in edidaktikum_theme e6b6ffccc3edcff8bbb58f1581fcec742f79d2c9
