### ISSUE TITLE
Keelata kasutajate liitumine mitte-aktiivse grupiga

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#415]

**Comment by hazarada** [comment]
Rohkem infot vaja, et kuidas viga reprodutseerida. Hetkel ei leidnud võimalust mitte aktsiivse grupiga liitumiseks.

**Comment by tammets** [comment]
http://edidaktikum.ee/et/content/ht-praktika-i

Juhul, kui on avalik ja mitte-aktiivne grupp, on link selleks grupi esilehel olemas.
