### ISSUE TITLE
Kutseomistamise portfoolio kasutajaliides on tõlgitav

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#421]
![screen shot 2016-06-17 at 9 26 57](https://cloud.githubusercontent.com/assets/380007/16142408/be058a64-346d-11e6-98c1-32c867688e3b.png)

![screen shot 2016-06-17 at 9 28 14](https://cloud.githubusercontent.com/assets/380007/16142438/e95e17a8-346d-11e6-9e54-bb65203f9146.png)

**Comment by GlebRed** [comment]
`'title_label' => t('Title'),`
`'label' => t('Description'),`
`'label' => t('Level'),`
`'label' => t('Choose a CV file'),`
`'label' => t('Choose an application file'),`

– peavad vist tõlgitavaid olema, nad kõik kasutavad `t(..)`

**Comment by GlebRed** [comment]
1.
![screen shot 2016-06-17 at 17 39 24](https://cloud.githubusercontent.com/assets/5457876/16154297/d445387a-34b2-11e6-9f64-6a906551ce00.png)
2.
![screen shot 2016-06-17 at 17 39 38](https://cloud.githubusercontent.com/assets/5457876/16154300/d7092bac-34b2-11e6-8576-7fc8e63a6656.png)
3.
![screen shot 2016-06-17 at 17 39 53](https://cloud.githubusercontent.com/assets/5457876/16154334/02853b90-34b3-11e6-9523-211e81c74404.png)

Ei saanud probleemi reprodutseerida. (

Võib-olla täis uninstall/install võiks aidata?
Mooduli väljalülitamiseks on vaja enne siin _admin/structure/types/manage/ed-q-portfolio/fields_ **Competence description** silla kustutada ja seepärast Home - Käivita cron. Seejärel moodul peab olema väljalülitamiseks ja uninstallimiseks võimeline.
