### ISSUE TITLE
Embed keskkonnast Google Drive

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#436]
Lisada võimalus embedida Google Drive-ist.

Näide:
`<iframe src="https://docs.google.com/spreadsheets/d/1jLp3tVz79H7elpO4pJ5tsnXrx1uQwZngK0vkDTtsxuA/pubhtml?widget=true&amp;headers=false"></iframe>`

**Comment by GlebRed** [comment]
Asi oli selles, et `docs.google.com/document/...` oligi lubatud, kuid siin on `docs.google.com/spreadsheets/...` 
Nüüd kõik, mis asuvad `docs.google.com/...` all on lubatud.
