### ISSUE TITLE
IE11 + Windows 7 scrollimine

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#467]
Kontrollida, kas esineb probleeme lehe kerimisel IE11+win7.

**Comment by hazarada** [comment]
Esilehekülje pildi parallax effekt ei tööta (IE 11 ei toeta transform-style:preserve-3d), tulemuseks tavaliselt keriv pilt. Muid probleeme ei tuvasta.

**Comment by hazarada** [comment]
Vaatasin saiti täpsemalt ja leidsin küll ühe juhuse kus scrollbar kaob, hetkel uurin.

**Comment by GlebRed** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/commit/4213adb6f568f7e62dff97696cdc72f860d88dcd
