### ISSUE TITLE
Vastamata Task'ide number valesti

### ISSUE THREAD

**Issue by hazarada** [centre-for-educational-technology/edidaktikum#470]
Dashboardil kuvatav number ei kattu päriselt vastamata või tagasi lükatud taskide numbriga.

**Comment by tammets** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/380007/24852751/4af494d0-1de1-11e7-83ad-b0bbe4a9240f.png)

**Comment by hazarada** [comment]
Hetkel bugi ei leidnud aga kahtlustan, et kuna üleval olev number näitab unanswered + rejected siis võivad paar rejected vastust taga pool olla. Pjotriga arutasime, ettepanekud on 
1. rejected vastused ülesse poole tuua 
2. paginatsiooni vähendada tõstes kuvatud vastuste arvu 
3. Lisada üles  statistiline teave nt. "Vastatud - x, Vastu võetud - y, Tagasi lükatud - z, Vastamata ..."

**Comment by tammets** [comment]
Nii on, rejected on numbri sees. Tõstame tagasilükatud vastused kõige ette (ettepoole vastamata ülesannetest).

**Comment by tammets** [comment]
Viga on endiselt üleval, rejected ülesandeid tudengil ei ole, kuid vastamata ülesandeid on mingi hulk numbreid:

![edidaktikum](https://user-images.githubusercontent.com/380007/39914748-a1073bce-550e-11e8-958b-1370e0a1d7fc.png)

**Comment by pjotrsavitski** [comment]
Nii, tundub et selle juures kasutatakse mitut erinevat funktsiooni: `ed_get_group_tasks`, `_ed_get_tasks_to_user` ja `_ed_get_group_tasks`.

Numbri jaoks kasutatakse esimest, minu testkasutaja puhul tagastab ta kuute erinevat ülesannet.

Nimekirja kuvamisel kasutatakse aga kahte teist meetodit koos. Nende tulemusena on näha ainult kolm ülesannet. Need ei ole omavahel kattumas.

Peaks nende loogikat uurima.

**Comment by tammets** [comment]
Pilet uuesti lahti, viga endiselt üleval:

![screen shot 2018-06-13 at 13 22 23](https://user-images.githubusercontent.com/380007/41345603-dc05e802-6f0c-11e8-9d9f-d0f429fd14cd.png)

**Comment by GlebRed** [comment]
Praegu isegi kui grupp ei ole aktiivne, tabelis näidatakse vastamata ülesannet. Kuid vastamata task'ide counter ei arvesta, kui grupp on mitteaktiivne. Kumb variant on õige?

**Comment by tammets** [comment]
Mitte aktiivse grupi taske ei arvestata. Grupp mitte aktiivne = grupi taske ei kuvata tabelis.
