### ISSUE TITLE
ed_field_full_name ja OAuth

### ISSUE THREAD

**Issue by GlebRed** [centre-for-educational-technology/edidaktikum#475]
Kasutajatel kes regasid ennast OAuth-i kaudu puudub `ed_field_full_name` väli. Selletõttu otsing ei saa neid leida kuni nad lisavad oma täisnime käsitsi profiili muutmislehel.

**Comment by pjotrsavitski** [comment]
Seda võiks lahendada nii, et registreerumisel vaadatakse kas kasutajal on täisnime väli tühi või mitte. Kui on tühi, proovitakse täita seda Hybridauth poolt tulnud väärtusega. Kui keellegi nimeks on "kiisu kiisu", siis saab kasutaja seda hiljem muuta.

Olemasolevate kontodega (kui selliseid veel on) võiks kirjutada migratsiooni mis käiks kõik kontod läbi ja prooviks vastavat välja täita (nime tuvastamise loogika oleks täpselt samasugune).
