### ISSUE TITLE
Select-väljade item-id omavad title-tag-i

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#476]
![screen shot 2017-01-06 at 13 44 48](https://cloud.githubusercontent.com/assets/380007/21716967/9fcd833c-d416-11e6-97bd-7839d9b0da43.png)

**Comment by pjotrsavitski** [comment]
Kas iga `<select>` välja iga element peaks saama `title` atribuuti mille seest leiab väärtust?

**Comment by tammets** [comment]
Pilet ei ole enam aktuaalne, kinni.
