### ISSUE TITLE
Input väljade tekst (kommentaarid) muuta kontrastsemaks

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#477]
#777

![screen shot 2017-01-10 at 13 21 10](https://cloud.githubusercontent.com/assets/380007/21806203/aca8343a-d740-11e6-94be-84c19dbab40f.png)

**Comment by pjotrsavitski** [comment]
Kas see kehtib ainult kommentaaridele või kõikidele väljadele (input[type="text"] ja textarea)? Kui kõikidele väljadele, siis kirjutaks pigem `form_control` klassi üle, sättides sinna uut väärtust.

Hetkel tundub väärtuseks olevat `#555555` mis ei tundu niivõrd väga hall olevat.

@tammets Kas see on veel aktuaalne või on meie uus välimus seda juba lahendanud?

**Comment by tammets** [comment]
Lahendatud peale uue kujunduse lisamist.
