### ISSUE TITLE
Kasutaja täisnime lisamine kohustuslik

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#484]
Kasutajad, kes loovad omale konto läbi oauthi, peavad esimesel sisenemisel täitma täisnime (_full name_) välja.

**Comment by pjotrsavitski** [comment]
Kas poleks mõistlikum kirjutada koodi, mis täidab täisnime automaatselt (esmasel registreerimisel või kontrollib sisse logimisel selle olemasolu ning vajadusel täidab olemasoleva infoga).

Kui info on juba olemas, siis pole vast vaja sundida kasutajat midagi täitma.

**Comment by pjotrsavitski** [comment]
Minu arust on ta juba nõutud väli nign vastavat vormi kuvatakse kasutajale peale Hybridauth'iga konto loomist. Kasutaja võib otsustada sellelt lehelt lahkuda, ilma täisnime lisamata. Kuid see on pigem issue #475 asi.

@tammets Mis sa arvad?

**Comment by pjotrsavitski** [comment]
Nime puudumist lahendatakse piletis #475
