### ISSUE TITLE
Ülesannete haldur kuvab ülesanded ajalises järjekorras

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#506]
Kuvatakse tähtaja järgi - varasemast tähtajast hilisemani. Hetkel kuvatakse lisamise järjekorras.

![screenshot](https://user-images.githubusercontent.com/380007/30036005-2704bffa-91b8-11e7-93aa-9fa52e0c6d50.png)

**Comment by pjotrsavitski** [comment]
This could be achieved by changing the `ed_get_group_tasks` function by adding `$q->orderBy('dd.ed_task_due_date_value', 'ASC');` in case `$b_due_date` is applied.

This would need the `if($desc) $q->orderBy('ogm.created', 'DESC' );` to be moved after that condition is possibly added. This way the first condition would be the main one (if added) and the second one would be supplemental, only affecting elements created within the same date.

This general method is being used in many places, would need to consider if this change would not affect any others. This change would affect order of the items if the **due_date** field is being requested from the database.
