### ISSUE TITLE
Task manager kuvab ka kasutajad, kes ei ole aktiivsed grupi liikmed

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#511]

**Comment by pjotrsavitski** [comment]
Meetod `ed_get_group_members` uus piirang `$q->condition('ogm.state', 1, '=');`
See tagastaks ainult aktiivseid kasutajaid, kuid see võiks mõjutada ka teisi kohti mis võiksid seda meetodit kasutada.

Päring on juba arvestamas ainult aktiivsete kasutajatega.

**Comment by pjotrsavitski** [comment]
Vaatasin kasutust. Hetkel on seda kasuatud kolmes kohas, mitte ükski neist ei tohiks mõjutatud olla.

igaks juhuks võib meetodile veel ühte parameetrit lisada, mis kontrollib selle piirangu rakendamist. Siis võime olla kindlad, et miski muus süsteemi osa poleks selle muudatuse poolt mõjutatud.
