### ISSUE TITLE
Uute materjalide arvu kuvamine grupi menüüs

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#524]
Sisseloginud kasutaja näeb grupi menüüs materjalide arvu, mis on tema poolt avamata peale viimast sisselogimist (nö värsked sisutüübid).

![screen shot 2017-11-28 at 14 44 26](https://user-images.githubusercontent.com/380007/33320424-e26a7d14-d44a-11e7-8f77-366c786a7c7f.png)

**Comment by pjotrsavitski** [comment]
Selle võimaldamiseks oleks me vaja säilitada infor sellt kohta mis kasutaja ja millal on mõne sisu lehte külastanud (oletan, et vaatamise all mõeldakse ikkagi täisvaadet mitte mõnda listing vaadet, kus on mitu erinevat objekti).

Selle abil saaks seda kõike sisuliselt teostada.

**Comment by tammets** [comment]
Mõeldud on täisvaadet, mitte listingut.
