### ISSUE TITLE
Lisada "Liitu"-nupp ka privaatsete gruppide juurde

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#541]
Nimekirjavaade:

![screen shot 2018-02-13 at 09 33 47](https://user-images.githubusercontent.com/380007/36138210-1cbdfc6a-10a1-11e8-9ae3-fe63e9741119.png)

**Comment by GlebRed** [comment]
Need on mitteaktiivsed grupid (ehk kasutajad ei saa liituda, ainult lahkuda).

**Comment by tammets** [comment]
Pilet kinni.
