### ISSUE TITLE
Faili lisamine G Drive, app isn't verified teade

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#543]
![screen shot 2018-02-13 at 09 47 05](https://user-images.githubusercontent.com/380007/36138664-fb0d1c5c-10a2-11e8-92c6-57bd6b917edf.png)

**Comment by pjotrsavitski** [comment]
See on vast HTTPS tõttu. Seda integrasiooni oleme ära unustanud. Peab ka seda muutma.

**Comment by GlebRed** [comment]
https://stackoverflow.com/questions/45437557/this-app-isnt-verified-this-app-hasnt-been-verified-by-google-yet-only-procee

https://support.google.com/code/contact/oauth_app_verification

**Comment by pjotrsavitski** [comment]
Sai korda.
