### ISSUE TITLE
Sisu font-weight 200->300

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#547]
200:

<img width="1237" alt="screen shot 2018-02-15 at 15 50 00" src="https://user-images.githubusercontent.com/380007/36259882-52bc6090-1268-11e8-801b-95be7f28c1b9.png">

300:

<img width="1271" alt="screen shot 2018-02-15 at 15 50 18" src="https://user-images.githubusercontent.com/380007/36259895-644cde84-1268-11e8-92af-8a55f112d196.png">

**Comment by GlebRed** [comment]
Closed in centre-for-educational-technology/edidaktikum_theme@dcd2a70ed431f8fdaae072d94cdbca72392f1e0d

**Comment by tammets** [comment]
Font muuta #727e85 -> #000

**Comment by GlebRed** [comment]
Closed in centre-for-educational-technology/edidaktikum_theme@08b0d2b8ac82605a76fb00c4ea6ba3f115b76626

**Comment by tammets** [comment]
Pilet uuesti avatud, sest font on taas nö. algne ja halvasti loetav.
