### ISSUE TITLE
Õppejõud ei saa kinnitada ootel tudengeid gruppidesse

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#562]

**Comment by GlebRed** [comment]
https://www.drupal.org/project/views_bulk_operations/issues/2254871

https://www.drupal.org/node/2527646

Rolled back views_bulk_operations to 7.x-3.2

**Comment by GlebRed** [comment]
Final in https://github.com/centre-for-educational-technology/edidaktikum/commit/9fa6f28fbc712354541c4bb386fdfb5c3d9db7ab
