### ISSUE TITLE
eD esilehel statistika ei ole nähtav

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#589]
![screen shot 2018-05-21 at 12 34 16](https://user-images.githubusercontent.com/380007/40302087-b4272df0-5cf6-11e8-9d6c-778ec71775a4.png)
![screen shot 2018-05-21 at 12 34 09](https://user-images.githubusercontent.com/380007/40302088-b4450de8-5cf6-11e8-9f43-786ec9f0fb63.png)

**Comment by GlebRed** [comment]
.parallax_03 klassil puudub `background-image: url("../img/parallax_03.jpg");`
