### ISSUE TITLE
Pädevuste taksonoomiat ei kuvata grupi loomise/muutmise vaates

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#590]
![screen shot 2018-05-21 at 14 32 55](https://user-images.githubusercontent.com/380007/40305768-a53c0b54-5d04-11e8-9086-c840adcc27b9.png)

**Comment by GlebRed** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/blob/951c9c96e0804bdda9e59e7540476c4cc9e6ae38/ed_cluster/ed_cluster.module#L2583
