### ISSUE TITLE
Gruppide esilehelt eemaldada G Drive failid

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#600]
Kuvada faile ainult gruppide failide nimekirjas.

![screen shot 2018-06-11 at 15 50 49](https://user-images.githubusercontent.com/380007/41232537-5dcd5a3e-6d8f-11e8-8e94-d8df25e59027.png)

**Comment by pjotrsavitski** [comment]
https://github.com/centre-for-educational-technology/edidaktikum_theme/commit/9c07867a173dbeb401e8d22127243c7fbd11f542
