### ISSUE TITLE
Inglisekeelsete tõlgete lisamine

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#620]
Inglisekeelsed tõlked lisada:

- Esileht (https://edidaktikum.ee/en/home)
- ~~Gruppide menüü (https://edidaktikum.ee/en/clusters)~~
- ~~Grupi pealeht~~
- ~~Õppematerjali üksikvaade~~
- ~~Kasutaja töölaud~~
- ~~Jalus~~

**Comment by pjotrsavitski** [comment]
Gruppide menüü sai korda, kui ma läksin sisse ja tegin (inglise keel sees), "Clear all caches". See on vast jälle selle vahemälu kahtlase käitumise taga, millele pole keegi kunagi suutnud mingit korrapärasust leida.

**Comment by pjotrsavitski** [comment]
Vabandan, korrapärasus on leitud (ehk pole see kõik kuid ikkagi).

Kui keeleks on **Eesti** ning keegi paneb **Clear all caches** protsessi käiku, siis jäävad kõik menüüd eestikeelseteks. Ma jugen arvata, et süsteem salvestab mällu nii nagu need on. Hiljem võetakse neid sealt välja, suure tõenäosusega lastes tõlkimissüsteemist läbi, kuid juba tõlgitud tekstidele ei leita vastet ning need jäävad nii nagu on. Kui need on aga ingliskeelsed, siis vastet saavad leitud ja kõik toimib.

**Comment by pjotrsavitski** [comment]
Forgot to put the correct reference to this commit https://github.com/centre-for-educational-technology/edidaktikum_theme/commit/5a3dad4edad434e34cb42c8c60f1e15504f27499
