### ISSUE TITLE
Tudengite nimed jäävad horisontaalselt "kerides" paika sarnaselt ülesannete pealkirjadega

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#637]
![2018-08-31 12 47 37](https://user-images.githubusercontent.com/380007/44905897-1bafdd80-ad1c-11e8-82d6-faaca5f3de61.gif)

**Comment by GlebRed** [comment]
Sticky header ei toimu korrektselt ka
![screenshot 2018-11-07 at 16 50 04](https://user-images.githubusercontent.com/5457876/48138687-8269ee00-e2ad-11e8-9140-937c8af0b456.png)
