### ISSUE TITLE
Grupi liikme(te) staatuse muutmisel kuvatakse veateade

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#638]
Tegevus salvestatakse ja kuvatakse veateade (tuvastamata juhul):

![screenshot](https://user-images.githubusercontent.com/380007/44906818-a691d780-ad1e-11e8-933f-2b17f9649667.png)

![screen shot 2018-08-31 at 13 04 31](https://user-images.githubusercontent.com/380007/44906824-ac87b880-ad1e-11e8-9f40-76136c561cab.png)

**Comment by pjotrsavitski** [comment]
Pole suutnud endal vastavat käitumist taasesitada. Häda ise on selles et `&` sümbol läheb kaotsi, kuid pole suutnud seda endal tekitada. Näiteks: õige oleks `?state=2748386&uid=` selle asemel on hoopiski `?state=2748386uid=`.

Pole suutnud ka edidaktikum.ee portaalis olevas testrühmas vastsvat käitumist taasesitada.
