### ISSUE TITLE
Grupi loomine, pädevuste lisamine, alamtasemed puudu

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#657]
Kasutajale kuvatakse ainult 2 ülemist taset:

![screenshot 2018-10-18 at 13 50 07](https://user-images.githubusercontent.com/380007/47149629-d603a000-d2dc-11e8-9ea3-05a487a71956.png)

**Comment by pjotrsavitski** [comment]
Resolved within another issue.

**Comment by GlebRed** [comment]
Closed in ecebc80dde804490554c8f272cea36a254f74e78
