### ISSUE TITLE
Ülesande loomisel saab määrata, mitu punkti maksimaalselt on võimalik ülesande eest saada

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#660]
Vahemik 0-100.

**Comment by pjotrsavitski** [comment]
Kas vaikimis väärtust on? Kas väli on kohustuslik? Mis oleks vaikimisi väärtus (kui vaikimisi väärtus on tühi string, siis mida . see tähendab)?

**Comment by tammets** [comment]
Vaikimisi väärtus puudub (st väli võib jääda tühjaks). Väli ei ole kohustuslik. Parandan, vahemik 1-100.
