### ISSUE TITLE
Facebookiga sisselogimine ei õnnestu

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#665]
<img width="553" alt="screenshot 2018-10-22 at 18 48 15" src="https://user-images.githubusercontent.com/380007/47302792-0f187900-d62b-11e8-9425-4ea7fe4dd5fe.png">

ja logi:

Exception: Could not authorize user. Bad request in Hybrid_Auth::initialize() (line 169 of /var/www/edidaktikum.ee/sites/all/libraries/hybridauth/Hybrid/Auth.php).

**Comment by pjotrsavitski** [comment]
Reconfigured according to module behaviour changes.

**Comment by GlebRed** [comment]
See on mooduli uuenduse tõttu :(
