### ISSUE TITLE
Ülesande vastust muutes muutub vastuse staatus "unchecked"

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#668]
Näiteks: vastus staatusega "accepted" -> tudeng muudab vastust, salvestab -> staatus "unchecked"
Näide 2: vastus staatusega "rejected" -> tudeng muudab vastust, salvestab -> staatus "unchecked"

Toimis järgnevalt enne piletit #656

**Comment by GlebRed** [comment]
Not related to #656
