### ISSUE TITLE
Kasutaja profiil, eraldada aktiivsed- ja mitteaktiivsed grupid

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#670]
![screenshot 2018-10-29 at 12 27 46](https://user-images.githubusercontent.com/380007/47644215-3795fb00-db76-11e8-87d2-0adf16b74d8f.png)

**Comment by pjotrsavitski** [comment]
Seems to be preprocessed in `edidaktikum.module` function `edidaktikum_user_view_alter`.

Might make sense to remove that code and add particular code on the theme side. The other solution is to process that element into two others.
