### ISSUE TITLE
Töölaud - ülesannete tabel tühi

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#687]
Ei kuvata aktiivse semestri ülesandeid:

![screenshot 2019-01-02 at 12 38 56](https://user-images.githubusercontent.com/380007/50588609-908e5200-0e8b-11e9-9840-52c983686891.png)

**Comment by GlebRed** [comment]
Jaanuari case

https://github.com/centre-for-educational-technology/edidaktikum/blob/9d683a1c9d0a60dd3dcf1f281b981eff010df079/ed_dashboard/ed_dashboard.module#L233

ja

https://github.com/centre-for-educational-technology/edidaktikum/blob/9d683a1c9d0a60dd3dcf1f281b981eff010df079/ed_dashboard/ed_dashboard.module#L487-L490

Ehk tekkib 2020 kuid peab olema 2019. Lisaks sellele, eelmise aasta ülesanded tulevad 2019 aasta parameetriga. `date('Y')` tõttu.
