### ISSUE TITLE
Kommentaari vaade + tõlked

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#690]
- [x] Uue kommentaari taustavärv eemaldada
- [x] Tõlked vastavalt ekraanipildile

![50627252-4a90c700-0f3b-11e9-99b9-5a4a16caa3d5](https://user-images.githubusercontent.com/380007/53799338-d8406100-3f42-11e9-9c68-a2315e83efa8.png)

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/pull/728
