### ISSUE TITLE
Kompaktsem Ülesannete halduri vaade

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#693]
- [x]  Filtreerimise nupp dropdowniga samale reale
- [x] Ülesannete nime asemel kuvada tähtaega, täpsem informatsioon avaneb popoveriga (ülesande nimi + tähtaeg)

![screenshot 2019-01-08 at 14 20 10](https://user-images.githubusercontent.com/380007/50830842-b31fdf80-1351-11e9-8f8f-b543915724de.jpg)

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/pull/706
