### ISSUE TITLE
Teavitus ülesande vastusele kommentaari laekumise kohta

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#707]
Ülesande vastusele lisatud uue kommentaari kohta saadetakse teade grupi halduri(te)le e-posti peale:
___
Kasutaja /nimi/ lisas uue kommentaari ülesande /ülesande nimi/ kasutaja /vastuse omanik kasutaja/ vastuse /link vastusele/ juurde.

Grupp: /Grupi nimi/
___

**Comment by leoste** [comment]
- [x] meil saadetakse kõigile grupi adminidele
- [ ] meili sisu
- [ ] seadetesse võimalus notifikatsiooni välja lülitada

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/pull/709

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/commit/ad58dc519cfefb53b38aa05bc6045c4c3c37ffdc

**Comment by leoste** [comment]
Meil saadetakse kõigile grupi adminidele, kes teavitust tahavad. Meil saadetakse ainult siis, kui answeri autor kommenteerib, ehk õpilane kommenteerib iseenda vastust.

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/pull/719
