### ISSUE TITLE
Gruppide listing, alammenüü ja sorteerimise valiku paigutus

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#711]
- [x] Sorteerimise kinnitamise nupp viia samale tasemele rippmenüüga
- [x] Uue grupi lisamise valikud liigutada gruppide listingu menüüsse

![screenshot 2019-02-19 at 10 25 38](https://user-images.githubusercontent.com/380007/53000704-a521ac00-3431-11e9-9844-d3afb5e7ff1f.png)

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/commit/2c926b6f25133fb1b54940c31d13d680c4df2492

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/pull/716
