### ISSUE TITLE
Task manager, tabeli päise positsioon

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#713]
Väiksemal ekraanil lehe kerides fikseerida task manageri tabeli päis lehe ülaserva.

![screenshot 2019-02-19 at 15 32 59](https://user-images.githubusercontent.com/380007/53018764-dfa03e80-345b-11e9-940b-a687038e5b58.png)
![screenshot 2019-02-19 at 15 32 24](https://user-images.githubusercontent.com/380007/53018765-dfa03e80-345b-11e9-92a4-a4d616b46ca1.png)

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum_theme/pull/80
