### ISSUE TITLE
Grupist lahkumise kinnitus, nupu sõnastus ja tõlge

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#725]
Eesti keeles nupule lisada kiri: Lahku grupist

![Screenshot 2019-03-13 at 10 55 50](https://user-images.githubusercontent.com/380007/54265757-b700f580-457e-11e9-8c47-6980c387787a.png)

**Comment by leoste** [comment]
lisasin tõlke
