### ISSUE TITLE
Lisa dropdowni ja filtreeri nupu vahele ruumi (ajaveeb, mustand - dashboard)

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#733]
![Screenshot 2019-04-08 at 13 24 50](https://user-images.githubusercontent.com/380007/55718040-6e185180-5a03-11e9-8d48-a05b22384f20.png)

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/pull/734
