### ISSUE TITLE
Ülesande looja saab piirata, kas vastata saab peale tähtaja möödumist

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#735]
![Screenshot 2019-05-14 at 11 25 39](https://user-images.githubusercontent.com/380007/57682829-3ff9e300-763b-11e9-901f-e3a0886400ce.png)

Tähtaja ületanud ülesandele vastust anda ei saa.

![Screenshot 2019-05-14 at 11 22 44](https://user-images.githubusercontent.com/380007/57682842-45efc400-763b-11e9-9671-15d40ff9d66b.png)

Kui vastust esitatakse ülesandele, millele on seatud piirang, kuvatakse ülesande lehel teksti:
"Peale tähtaega esitatud vastust ei salvestata!"

![Screenshot 2019-05-14 at 12 14 20](https://user-images.githubusercontent.com/380007/57686575-7edf6700-7642-11e9-8e28-2a804c18c902.png)

Enne vastamistähtaega alustatud vastamine lubab kasutajal vastuse salvestada ka peale tähtaja möödumist.

**Comment by pjotrsavitski** [comment]
Sel juhul peaks kasutajat sellest ehk ka teavitama ning näitama mõnda **countdown** tüüpi elementi, mis viitaks kui paju on kasutajal veel aega jäänud. Sellest oleks kasu kui kontroll toimib n.ö. sekundi pealt.

**Comment by leoste** [comment]
Kasutajamugavuse küljest oleks võibolla hea, kui sisemiselt tähtaeg oleks alles järgmise päeva varahommik (kell 5 vms). Mõned õpilased teevad asja suht hilja õhtul valmis ja kell 12 öösel, mil järgmine päev algab, võidakse alles tegemas olla. See hoiaks ära ka selle, et ei saa enam submittida nt kell 00:01 vms.
