### ISSUE TITLE
Ühtlustada Õppekavad ja Õpperühmad

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#752]
- Kõik Õpperühmad ümber nimetadada Õppekavad (Study group -> Curriculum)
- Kasutaja profiili all ja ülesande loomise / muutmise vaates kasutada Õppekava listingut

**Comment by GlebRed** [comment]
Ülesanne add/edit lehel: juhul kui "Määra kasutaja" on valitud, õppekavade list on deaktiveeritud
