### ISSUE TITLE
Kuvada aine kood grupi esilehe paremas veerus

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#756]
![Screenshot 2019-09-06 at 12 38 19](https://user-images.githubusercontent.com/380007/64418345-7c969200-d0a3-11e9-94bb-b99f5d90a813.png)

**Comment by GlebRed** [comment]
Closed in https://github.com/centre-for-educational-technology/edidaktikum_theme/commit/d397a0c86f21e27795f096774362803b2cf5e732
