### ISSUE TITLE
Grupi õppematerjalid, tõlkida nupp "new learning resource"

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#757]
![Screenshot 2019-09-06 at 12 42 36](https://user-images.githubusercontent.com/380007/64418537-de56fc00-d0a3-11e9-94d9-7fe69e0debdd.png)

**Comment by pjotrsavitski** [comment]
Täitsa olemas, ainult seda leiab kujul: `New Learning resource`
