### ISSUE TITLE
Lisada tõlked vastuste staatustele

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#758]
Kontrollimata
Tagasi lükatud
Kinnitatud
Kontrollitud

![Screenshot 2019-09-06 at 12 46 15](https://user-images.githubusercontent.com/380007/64418812-5b827100-d0a4-11e9-85e2-1e5145753265.png)

**Comment by pjotrsavitski** [comment]
Väljas juures peak kasutama `allowed_values_function` `allowed_values` asemel. Esimene võtab väärtused funktsiooni käest, jooksutades seda iga kord. Teine aga salvestab need kuhugi nadmebaasi ning keelest sõltuvaid anemeid selle juures kasutada ei tohiks.
