### ISSUE TITLE
Ülesande vastuse juures kuvada vastaja profiilipilti

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#779]
![Screenshot 2019-09-26 at 11 42 19](https://user-images.githubusercontent.com/380007/65673089-e37beb00-e052-11e9-8f56-647fce04096c.png)

**Comment by tammets** [comment]
Viia vastavusse ülaloleva pildiga (pilt+nimi, mitte nimi+pilt).

**Comment by leoste** [comment]
https://github.com/centre-for-educational-technology/edidaktikum/pull/842
