### ISSUE TITLE
Sisselogimise vaates liigutada HybridAuth alumiseks elemendiks

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#782]
+ h3 heading -> h4

![Screenshot 2019-09-27 at 11 43 04](https://user-images.githubusercontent.com/380007/65755598-1c33c700-e11c-11e9-9633-ef6d12d62da8.png)

**Comment by leoste** [comment]
h3 vahetada h4 oleks hybridauthi mooduli töö põhjal liialt tülikas olnud, nii et muutsin hoopis css, et selles konkreetses kohas h3 oleks h4 välimusega.
