### ISSUE TITLE
Uudiseid ei kuvata "värskemad eespool"

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#832]
Vt grupp https://edidaktikum.ee/et/node/123079/news ja uudis https://edidaktikum.ee/et/node/132291

**Comment by GlebRed** [comment]
<img width="308" alt="Screenshot 2020-04-23 at 13 06 12" src="https://user-images.githubusercontent.com/5457876/80097573-6ae6f980-8563-11ea-8a76-9370e0529374.png">

**Comment by tammets** [comment]
checkbox ei ole hea lahendus, see on lisa-klikk kasutajale. Vaikimisi sort -> uuemad eespool

**Comment by leoste** [comment]
lahendasin praegu nii, et uudiste näitamisel ei sorteerita sticky olemise järgi. uudist saab loomisel ikka märkida "püsib nimekirja alguses" aga sel pole enam mingit efekti.
