### ISSUE TITLE
Tudengitel ei ole võimalik postitada vastust ülesandele

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#849]
Veateade:

`EntityMalformedException: node liiki entiteedil puudub üks kogumi (bundle) omadus. in entity_extract_ids() (line 8006 of /var/www/edidaktikum.ee/includes/common.inc).`

Näiteks https://edidaktikum.ee/node/138036 juures.

**Comment by GlebRed** [comment]
Tühja grupi "learning outcomes" väljaga seotud

**Comment by GlebRed** [comment]
Lahendus: kustutada tühjad pädevused grupi tasemel
![Screenshot 2022-05-12 at 13 09 11](https://user-images.githubusercontent.com/5457876/168064227-5d243a75-698d-4afe-a033-912e86d86f3d.png)
