### ISSUE TITLE
Üliõpilase ja õppejõu tagasiside andmed ei kattu

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#867]
![Screenshot 2020-11-05 at 09 52 55](https://user-images.githubusercontent.com/380007/98212964-09113e80-1f4d-11eb-9e0a-1984ce17c56e.png)

https://edidaktikum.ee/et/node/144723/task-feedback

**Comment by GlebRed** [comment]
Permissions related
