### ISSUE TITLE
Kasutajad ei saa esitada vastust ülesandele

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#875]
<img width="623" alt="Screenshot 2021-05-28 at 10 25 13" src="https://user-images.githubusercontent.com/380007/119946180-07699f80-bf9f-11eb-964f-f5a7ec301945.png">
<img width="1213" alt="Screenshot 2021-05-28 at 10 25 06" src="https://user-images.githubusercontent.com/380007/119946184-089acc80-bf9f-11eb-9ec9-95cc7251c638.png">

**Comment by GlebRed** [comment]
Same as https://github.com/centre-for-educational-technology/edidaktikum/issues/849
