### ISSUE TITLE
Lisatud pädevusi ei kuvata grupi muutmise vaates

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#879]
https://edidaktikum.ee/et/content/kat7044-õppimise-sotsiaal-emotsionaalsed-aspektid2021-1-voor-ifiom-1-kamom-1-kukam-1-mlglm-1

Grupi https://edidaktikum.ee/et/node/160231/task-manager küljes on pädevused, mida ei kuvata muutmise vaates. Samas eksisteeriva ülesande juures neid kuvatakse: https://edidaktikum.ee/et/content/nutiseadmed-õppeprotsessis-fotograafia-võimalused

**Comment by tammets** [comment]
Probleem tekib grupi kloonimisel (koopia tegemisel). Koopiasse jäetakse väljad alles, originaalist eemaldatakse. Pädevused peavad salvestuma mõlemasse gruppi (koopia, originaal).

**Comment by pjotrsavitski** [comment]
Kirjeldan oukorda veidike täpsemalt. Nii koopia kui ka originaal on seotud samade pädevustega, mille viited paiknevad välja sees. Probleem on selles, et igal salvestamisel olemasolevaid pädevuste objekte kustutatakse, luuakse uued (vastavalt sellele kuidas vormi seis jäi) ning kirjutatatkse vastava seoste välja uute identifikaatoritega üle. Kui aga kahel grupil on samad pädevused, siis ühe üle salvestamisel olemasolevad kustuvad, uued saavad loodud, teisel gruppil aga jäävad viited kustunud pädevustele. Välja väärtused on alles, kuid viidetud objektid enam ei eksisteeri.
