### ISSUE TITLE
Asenda grupi (õpiväljundi) pädevuste lisamise lahendus

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#889]
Kasuta lahendust sarnaselt ajaveebi postitusega:

![Screenshot 2021-10-29 at 18 44 04](https://user-images.githubusercontent.com/380007/139464350-8300f8db-0a10-4407-a1df-03f8ffb30e28.png)

Lahendus vastab järgmistele tingimustele:
- kasutaja saab valida korraga **mitut** alamtaseme item-it
- kasutaja saab valida **ainult** kõige alumise taseme item-eid

**Comment by pjotrsavitski** [comment]
Need pole grupi vaid hoopiski üksikute õpiväljundite pädevused.
