### ISSUE TITLE
Profiili lisainfo ei kuvata kasutaja e-posti ja asutust

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#934]
<img width="779" alt="Screenshot 2023-06-27 at 15 27 57" src="https://github.com/centre-for-educational-technology/edidaktikum/assets/380007/5f3a19dc-e91e-4acc-a98b-8ba7de3b3ac3">

**Comment by GlebRed** [comment]
Closed in https://github.com/centre-for-educational-technology/edidaktikum_theme/commit/271c160a6911b7fb611e0761a29c8bb03f95f590
