### ISSUE TITLE
Eemaldada UserVoice tagasiside aken

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/edidaktikum#942]
Eemaldada UserVoice tagasiside aken seoses teenuse tasuliseks muutumisega.

<img width="435" alt="Screenshot 2024-07-21 at 19 05 31" src="https://github.com/user-attachments/assets/04e6f5c7-3f7b-4cbf-933d-3ca8dca363d2">

**Comment by GlebRed** [comment]
Closed in ee4f8f7e2a5c3c5b4831880e3ba9cc1a7785e397
